### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by RobbieTheWagner** [sir-dunxalot/ember-blog#10]
Hi @sir-dunxalot, keep finding more and more repos where you have implemented things I need 😄 . Does this still work? If not, have you experimented with generating static blog pages with something like hexo or hugo and embedding the output in an ember app? I'm trying to determine the best way to host my blog inside my ember app, as navigating away to ghost right now, is not ideal.

**Comment by sir-dunxalot** [comment]
Glad to hear that! Haha.

For the most part, yes this does work. A few people have picked it up over the last couple of months though Ember Data 2.0 brought a couple of changes that could be improved in the library. For example, removing the fixtures adapter in favor of a custom adapter. I haven't run this with the latest version of Ember so I imagine there are other small tweaks to continue functionality.

I'm definitely trying to maintain this repo as needed though - I'd probably be able to find some time today or this week to do some investigation.

**Comment by RobbieTheWagner** [comment]
@sir-dunxalot I'm willing to help out, if you could help me understand the tasks that need to be done to improve this. I'm currently using ghost for my blog, and want to pull it into my app instead as soon as I can.
