### ISSUE TITLE
compass dependencies not captured

### ISSUE THREAD

**Issue by adamrneary** [sir-dunxalot/ember-blog#5]
When I compile (`brunch watch -s`) I am getting app.css with "ERROR: Cannot load compass." 

1. If compass is a dependency, we should capture that within npm install (or add a gemfile? seems odd to have a ruby dependency?)
2. In the meantime would you mind confirming which versions of sass and compass you're using?

**Comment by sir-dunxalot** [comment]
Closed with rebuild - addon now has a complete rewrite and focusses on adding to an existing Ember app only (not doing any styling).
