### ISSUE TITLE
Ember-cli 0.2.5 _templateCompiler no longer exists

### ISSUE THREAD

**Issue by sukima** [sir-dunxalot/ember-blog#7]
Seems [`_templateCompiler`](https://github.com/sir-dunxalot/ember-blog/blob/57e37a61434c6171188b25edb3f4a534d96f5ea5/index.js#L57) no longer exists. In fact a `console.log` reveals the following:

    { name: 'ember-cli-htmlbars', ext: 'hbs', toTree: [Function] }

This is probably a breaking change in ember-cli 0.2.5 especially because of the use of a non-documented private function. Any idea where it might have been moved to?

**Comment by sir-dunxalot** [comment]
So this issued arises when the `ember-cli-htmlbars` is less than `0.7.7`. Perhaps you have a lower version in your app that is overriding the addon's version?

**Comment by sukima** [comment]
Well that's odd a brand new app fresh out of the ember-cli 0.2.5 `new` command sets the `ember-cli-htmlbars` dependency in `package.json` to `0.7.6`. WTF?!

Thanks for the input.

**Comment by sir-dunxalot** [comment]
No problem - I assume that fixed it? The `_templateCompiler` property is private to this addon but I experienced the same [issue](https://github.com/ember-cli/ember-cli-htmlbars/issues/55).

**Comment by sukima** [comment]
@sir-dunxalot Yes, forcing the `ember-cli-htmlbars` to `0.7.7` in my `package.json` works. Perhaps it is worth a note in the README that the latest `ember-cli` creates a `package.json` file that is outdated.

**Comment by sir-dunxalot** [comment]
Sounds good - I will add a warning and will keep this issue open until that's fixed.

**Comment by sir-dunxalot** [comment]
Fixed with #8
